<a href="https://colab.research.google.com/github/mrCarterData/Numpy/blob/main/DataProccessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
A = [1 , 2 , 54 , 12]
print(A)
print(type(A))

[1, 2, 54, 12]
<class 'list'>


In [ ]:
import numpy as np
my_array = np.array(A)

Basically numpy is used for all the mathematical calculation.

In [ ]:
print(my_array)

[ 1  2 54 12]


In [ ]:
type(my_array)

numpy.ndarray

In [ ]:
# not allowed with list
print(A + 5)

TypeError: ignored

In [ ]:
print(my_array + 5)

[ 6  7 59 17]


In [ ]:
# 2 Dimensional Array

b = np.array([38 , 23 , 32 , 64])
a = np.array([[38 , 23 , 32 , 64] , [83 , 31 , 21, 46]])
print(b)
print('----')
print(a)

[38 23 32 64]
----
[[38 23 32 64]
 [83 31 21 46]]


In [ ]:
lst = [10,200,400,0]

lst_new = lst+10
print(lst_new)

TypeError: ignored

In [ ]:
import numpy as np
arr = np.array(lst)
ar_new = arr+10
print(ar_new)

[ 20 210 410  10]


Shape of an array

In [ ]:
# shape
a = np.array([1,2,3,4]) # 1-D array
b = np.array([[1,2,3,4],[5,6,7,8]]) # 2-D array

# for checking the shaoe of both the array
print(a.shape)
print(b.shape)

(4,)
(2, 4)


In [ ]:
# ndim -> fucntion
print(a.ndim)
# it will give you the dimession of an array
print(b.ndim)


1
2


In [ ]:
print(a.size)
print(b.size)
# size ()-> it used for fiuncing the number of values in an array

4
8


In [ ]:
# itemsize
print(a.itemsize)
print(b.itemsize)
# the values stored at location(it memory size)

8
8


In [ ]:
# reshape() help us to reshape our array.
z = np.array([5,6,7,45,12,52]).reshape(2,3)
print(z)


[[ 5  6  7]
 [45 12 52]]


Matrix ->. It is form of an array

In [ ]:
x = np.matrix([[1,2,3],[3,4,5],[6,7,8]])
print(x)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Excercise :-

import numpy as npy

marks = [20,30,40]
ids = [0,2,4]

print(marks)
print(ids)

[20, 30, 40]
[0, 2, 4]


In [ ]:
arr1 = np.array([25,56,12,85,34,75])

arr2 = [42,3,86,32,856,46]

Narr = np.array([1,2,3,4,5,6])


In [ ]:
new_arr = arr1.astype(complex)
print(new_arr)

[25.+0.j 56.+0.j 12.+0.j 85.+0.j 34.+0.j 75.+0.j]


Indexing

In [30]:
name = 'Carter'
# print only 'e' from carter
x = name[4]
print(x)

e


In [33]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# pull out second element of the 3 rd row
print(a)
print(a[2][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8


In [34]:
# pull out 1st two rows and columns
print(a[:2,:2])

[[1 2]
 [4 5]]


In [36]:
# pull out all elements of the 3rd row
print(a[2, :])

[7 8 9]


Integer Array Indexing

In [38]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# pull out the 1st elemetn from 1st row 2 and element from 2nd row and the 1st element from the 3rd row
print(a[[0,1,2],[0,1,0]])

[1 5 7]


In [41]:
a = np.array([[4,7,1],[2,5,7],[7,1,1]])
mask = a > 3
print(mask)

print(a[mask])

[[ True  True False]
 [False  True  True]
 [ True False False]]
[4 7 5 7 7]


Vectorisation : It abliity of NumPy by whihc we can perform operations on entire array greater than or less than 2.